### PR TITLE
[Fix] Should work in Electron environment

### PR DESCRIPTION
**Pull request by VadimKorobka**

### CODE REVIEW

**Comment by kevincastejon** [comment]
hi, thanks for PR
Are you saying that the 'node-fetch' package does not work on Electron environment?

**Comment by VadimKorobka** [comment]
Yes

**Comment by kevincastejon** [comment]
Sorry for long delay, I have tested node-fetch into an Electron app and it's working just fine. If you encounter issues between node-fetch and Electron maybe open an issue on one or the other repo.

**Comment by VadimKorobka** [comment]
Your module contains a fundamental error. Using a program that uses your module with an entire office **(200+ devices)** through a wide channel with **one white IP address** will lead to **blocking**.

**Comment by kevincastejon** [comment]
Can you tell me more about this error? Did you try to change the testing url or did you stick on default google one? What are you calling "white" IP address?

**Pull request closed without merging**
